import Head from 'next/head';
import TerrainOverview from '../../../components/TerrainOverview';
import InfoPageLayout from '../../../layouts/InfoPageLayout';
import { getAllResortNames, getResort } from '../../../services/resortsService';
import { ResortNameObj } from '../../../types';

interface Props {
  resortInfo: any;
}

const SkiResort = ({ resortInfo }: Props) => {
  console.log(resortInfo);

  return (
    <div>
      <Head>
        <title>On The Snow Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InfoPageLayout>
        <TerrainOverview />
      </InfoPageLayout>
    </div>
  );
};

export const getStaticPaths = async () => {
  const resorts = await getAllResortNames();
  const paths = resorts.map(
    (resort: ResortNameObj) => `/resort/${resort.id}/ski-resort`,
  );
  return { paths, fallback: false };
};

type SlugParams = {
  resort: string;
};

interface Props {
  params: SlugParams;
}

export const getStaticProps = async ({ params }: Props) => {
  const { resort } = params;
  const resortInfo = await getResort(resort);
  return {
    props: { resortInfo },
  };
};

export default SkiResort;
