import Head from 'next/head';
import ResortsList from '../components/ResortsList';
import { getAllResortNames } from '../services/resortsService';
import InfoPageLayout from '../layouts/InfoPageLayout';
import styles from '../styles/Home.module.css';
import { ResortNameObj } from '../types';

interface Props {
  resorts: ResortNameObj[];
}

const Home = ({ resorts }: Props) => {
  return (
    <div>
      <Head>
        <title>On The Snow Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InfoPageLayout>
        <ResortsList resorts={resorts} />
      </InfoPageLayout>
    </div>
  );
};

export const getStaticProps = async () => {
  const resorts = await getAllResortNames();
  return {
    props: { resorts },
  };
};

export default Home;
