import Head from 'next/head';
import ResortsList from '../../components/CardContents/ResortsList';
import {
  getStateNames,
  getStateResortNames,
} from '../../services/resortsService';
import InfoPageLayout from '../../layouts/InfoPageLayout';
import { slugify } from '../../utilities/slug';
import { ResortNameObj } from '../../types';

interface Props {
  resorts: ResortNameObj[];
}

const StateSkiResorts = ({ resorts }: Props) => {
  return (
    <div>
      <Head>
        <title>On The Snow Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InfoPageLayout>
        <ResortsList resorts={resorts} />
      </InfoPageLayout>
    </div>
  );
};

export const getStaticPaths = async () => {
  const states = await getStateNames();
  const paths = states.map((state: string) => `/${slugify(state)}/ski-resorts`);
  return { paths, fallback: false };
};

type StateParams = {
  state: string;
};

interface Props {
  params: StateParams;
}

export const getStaticProps = async ({ params }: Props) => {
  const { state } = params;
  const resorts = await getStateResortNames(state);
  return {
    props: { resorts },
  };
};

export default StateSkiResorts;
